package com.computec.vista;

public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_PanelPrincipal = new javax.swing.JTabbedPane();
        jPanel_Inicio = new javax.swing.JPanel();
        jPanel_Bienvenida = new javax.swing.JPanel();
        etqBienvenida = new javax.swing.JLabel();
        jPanel_Botones = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnEquipos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jPanel_Clientes = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        btnInicioClientes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel_Equipos = new javax.swing.JPanel();
        jPanel_Ventas = new javax.swing.JPanel();
        jPanel_Reportes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión Computec");
        setResizable(false);

        jPanel_Inicio.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_Bienvenida.setBackground(new java.awt.Color(0, 51, 153));

        etqBienvenida.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        etqBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        etqBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqBienvenida.setText("BIENVENIDO A COMPUTEC");

        javax.swing.GroupLayout jPanel_BienvenidaLayout = new javax.swing.GroupLayout(jPanel_Bienvenida);
        jPanel_Bienvenida.setLayout(jPanel_BienvenidaLayout);
        jPanel_BienvenidaLayout.setHorizontalGroup(
            jPanel_BienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etqBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        jPanel_BienvenidaLayout.setVerticalGroup(
            jPanel_BienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BienvenidaLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(etqBienvenida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Botones.setBackground(new java.awt.Color(255, 255, 255));

        btnClientes.setBackground(new java.awt.Color(0, 51, 153));
        btnClientes.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Ir a Clientes");
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setMaximumSize(new java.awt.Dimension(170, 60));
        btnClientes.setMinimumSize(new java.awt.Dimension(170, 60));
        btnClientes.setPreferredSize(new java.awt.Dimension(170, 60));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnEquipos.setBackground(new java.awt.Color(0, 51, 153));
        btnEquipos.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        btnEquipos.setForeground(new java.awt.Color(255, 255, 255));
        btnEquipos.setText("Ir a Equipos");
        btnEquipos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEquipos.setMaximumSize(new java.awt.Dimension(170, 60));
        btnEquipos.setMinimumSize(new java.awt.Dimension(170, 60));
        btnEquipos.setPreferredSize(new java.awt.Dimension(170, 60));
        btnEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquiposActionPerformed(evt);
            }
        });

        btnVentas.setBackground(new java.awt.Color(0, 51, 153));
        btnVentas.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setText("Ir a Ventas");
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.setMaximumSize(new java.awt.Dimension(170, 60));
        btnVentas.setMinimumSize(new java.awt.Dimension(170, 60));
        btnVentas.setPreferredSize(new java.awt.Dimension(170, 60));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(0, 51, 153));
        btnReportes.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Ir a Reportes");
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setMaximumSize(new java.awt.Dimension(170, 60));
        btnReportes.setMinimumSize(new java.awt.Dimension(170, 60));
        btnReportes.setPreferredSize(new java.awt.Dimension(170, 60));
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BotonesLayout = new javax.swing.GroupLayout(jPanel_Botones);
        jPanel_Botones.setLayout(jPanel_BotonesLayout);
        jPanel_BotonesLayout.setHorizontalGroup(
            jPanel_BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BotonesLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel_BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel_BotonesLayout.setVerticalGroup(
            jPanel_BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BotonesLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        javax.swing.GroupLayout jPanel_InicioLayout = new javax.swing.GroupLayout(jPanel_Inicio);
        jPanel_Inicio.setLayout(jPanel_InicioLayout);
        jPanel_InicioLayout.setHorizontalGroup(
            jPanel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InicioLayout.createSequentialGroup()
                .addComponent(jPanel_Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_InicioLayout.setVerticalGroup(
            jPanel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane_PanelPrincipal.addTab("Inicio", jPanel_Inicio);

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnInicioClientes.setBackground(new java.awt.Color(0, 51, 153));
        btnInicioClientes.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        btnInicioClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioClientes.setText("Ir al Inicio");
        btnInicioClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicioClientes.setMaximumSize(new java.awt.Dimension(130, 40));
        btnInicioClientes.setMinimumSize(new java.awt.Dimension(130, 40));
        btnInicioClientes.setPreferredSize(new java.awt.Dimension(130, 40));
        btnInicioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioClientesActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Datos Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Medium ITC", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(764, Short.MAX_VALUE)
                .addComponent(btnInicioClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(btnInicioClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_ClientesLayout = new javax.swing.GroupLayout(jPanel_Clientes);
        jPanel_Clientes.setLayout(jPanel_ClientesLayout);
        jPanel_ClientesLayout.setHorizontalGroup(
            jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_ClientesLayout.setVerticalGroup(
            jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane_PanelPrincipal.addTab("Clientes", jPanel_Clientes);

        javax.swing.GroupLayout jPanel_EquiposLayout = new javax.swing.GroupLayout(jPanel_Equipos);
        jPanel_Equipos.setLayout(jPanel_EquiposLayout);
        jPanel_EquiposLayout.setHorizontalGroup(
            jPanel_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel_EquiposLayout.setVerticalGroup(
            jPanel_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jTabbedPane_PanelPrincipal.addTab("Equipos", jPanel_Equipos);

        javax.swing.GroupLayout jPanel_VentasLayout = new javax.swing.GroupLayout(jPanel_Ventas);
        jPanel_Ventas.setLayout(jPanel_VentasLayout);
        jPanel_VentasLayout.setHorizontalGroup(
            jPanel_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel_VentasLayout.setVerticalGroup(
            jPanel_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jTabbedPane_PanelPrincipal.addTab("Ventas", jPanel_Ventas);

        javax.swing.GroupLayout jPanel_ReportesLayout = new javax.swing.GroupLayout(jPanel_Reportes);
        jPanel_Reportes.setLayout(jPanel_ReportesLayout);
        jPanel_ReportesLayout.setHorizontalGroup(
            jPanel_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel_ReportesLayout.setVerticalGroup(
            jPanel_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jTabbedPane_PanelPrincipal.addTab("Reportes", jPanel_Reportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        jTabbedPane_PanelPrincipal.setSelectedIndex(3);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquiposActionPerformed
        jTabbedPane_PanelPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_btnEquiposActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        jTabbedPane_PanelPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        jTabbedPane_PanelPrincipal.setSelectedIndex(4);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnInicioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioClientesActionPerformed
        jTabbedPane_PanelPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_btnInicioClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEquipos;
    private javax.swing.JButton btnInicioClientes;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel etqBienvenida;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Bienvenida;
    private javax.swing.JPanel jPanel_Botones;
    private javax.swing.JPanel jPanel_Clientes;
    private javax.swing.JPanel jPanel_Equipos;
    private javax.swing.JPanel jPanel_Inicio;
    private javax.swing.JPanel jPanel_Reportes;
    private javax.swing.JPanel jPanel_Ventas;
    private javax.swing.JTabbedPane jTabbedPane_PanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
